# Generated by Django 6.0 on 2026-01-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='fallback_image',
            field=models.ImageField(blank=True, null=True, upload_to='fallbacks/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/'),
        ),
    ]
